fragment post on Post {
	 id
    title
    body
    indexRef
    createdAt
}

query GET_POST {
  post1: post (id: 860) {
  	...post
	}

	 post2: post(id: 783) {
  	...post
	}

	 post3: post (id: 15) {
  	...post
	}
}
